
[env]
CARGO_MAKE_DOCS_README_SET_CRATE_VERSION = true

[config]
additional_profiles = [
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "ci-static-code-analysis-tasks",
    "publish-pre-cleanup"
]
